export const GIFJSON = {
  On: require("./asset/Json/cal.json"),
  Call: require("./asset/Json/call.json"),
  Video: require("./asset/Json/video.json"),
  History: require("./asset/Json/history.json"),
  People: require("./asset/Json/people.json"),
  Phone: require("./asset/Json/phone.json"),
  Loading: require("./asset/Json/loading.json"),
  LoadingChat: require("./asset/Json/loadingchat.json"),
  Robot: require("./asset/Json/robot.json"),
  Welcome: require("./asset/Json/welcome.json"),
  Typing: require("./asset/Json/typing.json"),
  Camera: require("./asset/Json/camera.json"),
  Logout: require("./asset/Json/logout.json"),
  ReName: require("./asset/Json/reName.json"),
  AddPeople: require("./asset/Json/addPeople.json"),
  Trash: require("./asset/Json/trash.json"),
  Group: require("./asset/Json/group.json"),
};
